"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class moved_t(object):
    """ Reports from 'it' when they move. """

    __slots__ = ["id", "new_position"]

    __typenames__ = ["int8_t", "int16_t"]

    __dimensions__ = [None, [2]]

    def __init__(self):
        self.id = 0
        """ LCM Type: int8_t """
        self.new_position = [ 0 for dim0 in range(2) ]
        """ LCM Type: int16_t[2] """

    def encode(self):
        buf = BytesIO()
        buf.write(moved_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.id))
        buf.write(struct.pack('>2h', *self.new_position[:2]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != moved_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return moved_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = moved_t()
        self.id = struct.unpack(">b", buf.read(1))[0]
        self.new_position = struct.unpack('>2h', buf.read(4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if moved_t in parents: return 0
        tmphash = (0xf1ce5210d53f1a26) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if moved_t._packed_fingerprint is None:
            moved_t._packed_fingerprint = struct.pack(">Q", moved_t._get_hash_recursive([]))
        return moved_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", moved_t._get_packed_fingerprint())[0]

