"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class report_status_t(object):
    """ Used for intermittent checkin to make sure everyone is on the same page. """

    __slots__ = ["id", "position", "game_started", "frozen"]

    __typenames__ = ["int8_t", "int16_t", "boolean", "boolean"]

    __dimensions__ = [None, [2], None, None]

    def __init__(self):
        self.id = 0
        """ LCM Type: int8_t """
        self.position = [ 0 for dim0 in range(2) ]
        """ LCM Type: int16_t[2] """
        self.game_started = False
        """ LCM Type: boolean """
        self.frozen = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(report_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.id))
        buf.write(struct.pack('>2h', *self.position[:2]))
        buf.write(struct.pack(">bb", self.game_started, self.frozen))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != report_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return report_status_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = report_status_t()
        self.id = struct.unpack(">b", buf.read(1))[0]
        self.position = struct.unpack('>2h', buf.read(4))
        self.game_started = bool(struct.unpack('b', buf.read(1))[0])
        self.frozen = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if report_status_t in parents: return 0
        tmphash = (0x395e58f303a288b7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if report_status_t._packed_fingerprint is None:
            report_status_t._packed_fingerprint = struct.pack(">Q", report_status_t._get_hash_recursive([]))
        return report_status_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", report_status_t._get_packed_fingerprint())[0]

